### PR TITLE
Add OpenCycleMap option to layer switcher

### PR DESCRIPTION
**Pull request by mvl22**
OpenCycleMap is a very popular OSM tileset. We would find this a very useful background to have available.

### CODE REVIEW

**Comment by mvl22** [comment]
NB I have made contact with the maintainer of the OpenCycleMap server whose bandwidth would be used, @gravitystorm, and he has no objections.

**Comment by dmofot** [comment]
Just an FYI, but you can add any tileset you want through Meta -> Add map layer.  I just added [OCM](http://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png) and it worked flawlessly and adds a little checkbox to turn it on/off down in the lower right corner.  Probably a better option that trying to accommodate every tileset in the switcher.

image

**Comment by tmcw** [comment]
:+1:

**Comment by mvl22** [comment]
Cheers :)

**Pull request merged**
