### PR TITLE
Quick fix to solve issue #459 (unicode decoding problem when loading …

### PR DESCRIPTION
**Pull request by Loufylouf**
…geojson from Github).

### CODE REVIEW

**Comment by jeekajoo** [comment]
fixes #459 (commenting to add the reference)

**Comment by Loufylouf** [comment]
I also added the possibility to update files on Github instead of having to create a new one. Should be in a separate pull request, but I can't find how to do that.

**Comment by tmcw** [comment]
Thanks, merged!

**Comment by Loufylouf** [comment]
You're welcome. I haven't updated the generated files site.js and site_mobile.js, because, well they should be generated instead of taken straight from Github, but I can understand that for an easy distribution it might be better, so you might have to add a commit with the content of the files updated.

**Comment by jeekajoo** [comment]
Thanks much to both of you!

**Pull request merged**
